- name: install epel
  yum:
    name: epel-release
    state: present
  when: inventory_hostname == groups['web'][0]


- name: Install nginx
  yum:
    name: nginx
    state: present
  when: inventory_hostname == groups['web'][0]


- name: Install audispd-plugins
  yum:
    name: audispd-plugins
    state: present
  when: inventory_hostname == groups['web'][0]


- name: Copy timezone
  copy:
    src: "/usr/share/zoneinfo/Europe/Moscow"
    dest: /etc/localtime
    remote_src: yes


- name: restart chronyd
  systemd:
    name: chronyd
    enabled: yes
    state: restarted


- name: Add audit.rules
  lineinfile:
    dest: /etc/audit/rules.d/audit.rules
    state: absent
    line: |
      -w /etc/nginx/nginx.conf -p wa -k nginx_conf
      -w /etc/nginx/default.d/ -p wa -k nginx_conf
  when: inventory_hostname == groups['web'][0]

    
- name: load nginx.conf
  template:
    src: "nginx.conf.j2"
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == groups['web'][0]


- name: restart nginx
  systemd:
    name: nginx
    enabled: yes
    state: restarted
  when: inventory_hostname == groups['web'][0]


- name: load auditd.conf
  template:
    src: "auditd.conf.j2"
    dest: /etc/audit/auditd.conf
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == groups['web'][0]

- name: load nginx.conf
  template:
    src: "au-remote.conf.j2"
    dest: /etc/audisp/plugins.d/au-remote.conf
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == groups['web'][0]

- name: load nginx.conf
  template:
    src: "audisp-remote.conf.j2"
    dest: /etc/audisp/audisp-remote.conf
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == groups['web'][0]


- name: Restart auditd
  systemd:
    name: auditd
    enabled: yes
    state: restarted
  when: inventory_hostname == groups['web'][0]


- name: load nginx.conf
  template:
    src: "rsyslog.conf.j2"
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: '0644'
  when: inventory_hostname == groups['log'][0]


- name: Restart rsyslog
  systemd:
    name: rsyslog
    enabled: yes
    state: restarted
  when: inventory_hostname == groups['log'][0]